name: flutter_debug_drawer
description: Adds a side menu in all screens with debug information. You can decide which information to show and create new modules to show information.
author: Sergi Mart√≠nez <sergi.martinez@gmail.com>
homepage: https://github.com/sergiandreplace/flutter_debug_drawer
version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0+3
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:

flutter:
  uses-material-design: true
